### PR TITLE
Run the Generator (from Proto-generated JSON Schemas) – Nov 3, 2020

### LINKED ISSUE #24: Use /* */ header comment per Java Style
We should use headers:

```
/*
 *
 */
```

Like other java libraries

### PR DESCRIPTION
**Pull request by grant**
- Generates this library.
  - Last generation used manually-created JSON Schemas.
    - Uses the latest `qt` generator (which uses proto-generated jsonschemas)
  - Updates the generator with our single pom setup. (This is already what the library uses, just updates the gen steps so they work)

> Note: The license header `http` diff is a slight mistake fixed in https://github.com/googleapis/google-cloudevents/pull/104. Shouldn't be a blocker.

Fixes: https://github.com/googleapis/google-cloudevents-java/issues/24
CC: @chingor13

### CODE REVIEW

**Review by jskeet — COMMENTED** [review]
Is the plan to merge https://github.com/googleapis/google-cloudevents/pull/104 and rebase?

Not sure how much of the rest to review - the first couple of screens-worth look okay, but I'm not sure what to look for.

**Comment by grant** [comment]
> Is the plan to merge [googleapis/google-cloudevents#104](https://github.com/googleapis/google-cloudevents/pull/104) and rebase?

They're different repos.Just merged.

**Comment by grant** [comment]
> Not sure how much of the rest to review - the first couple of screens-worth look okay, but I'm not sure what to look for.

Repos in this org require an approving review to merge, I'm not really expecting comments on generated PRs.

**Comment by jskeet** [comment]
> They're different repos.Just merged.

Okay, in my tired state I mis-spoke - I meant "are you going to rerun the generator once you've merged the change". Because this PR changes https to http in the licence text, and the generator change will mean that it's back to https, yes? It would be best to minimize the churn on that sort of thing.

**Comment by grant** [comment]
Yes, I can wait for the license fix to get in before merging this PR to prevent churn.

Need these PRs merged:

- https://github.com/googleapis/google-cloudevents/pull/103
- https://github.com/googleapis/google-cloudevents/pull/104

Then I'll regen this PR which won't have that https error.

**Review by grayside — APPROVED** [review]
This makes sense to me from an overall perspective but I am not reviewing for Java practices perspective.

**Pull request merged**
